server.port=9090
spring.datasource.url=jdbc:postgresql://ep-fancy-dream-ap7t48do-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_oSYCu7JNed0H
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=MySuperSecretKeyForJWTThatIsAtLeast32CharactersLong12345
spring.mail.host=smtp.gmail.com
file.upload-dir=uploads/resumes
spring.mail.port=587
spring.mail.username=manideep685@gmail.com
spring.mail.password=waqo tqzm yair iyee
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}