spring.datasource.url=jdbc:postgresql://localhost:5432/statusofapplication
spring.datasource.username=postgres
spring.datasource.password=Deepu@123
jwt.secret=MySuperSecretKeyForJWTThatIsAtLeast32CharactersLong123456
spring.mail.username=manideep685@gmail.com
spring.mail.password=waqo tqzm yair iyee